FROM ubuntu:20.04
MAINTAINER Ar4k - Rossonet <andrea.ambrosini@rossonet.com>
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y openjdk-8-jre redis redis-server redis-sentinel redis-tools && apt-get clean && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["java"]
CMD ["-XX:+UnlockExperimentalVMOptions","-Djava.net.preferIPv4Stack=true","-XX:+UseCGroupMemoryLimitForHeap","-XshowSettings:vm","-Djava.security.egd=file:/dev/./urandom","-jar","/agent.jar"]
COPY *-all.jar agent.jar
