#FROM ubuntu:20.04
FROM apache/nifi:1.18.0
ARG MAINTAINER="Andrea Ambrosini <andrea.ambrosini@rossonet.org>"
ENTRYPOINT ["java"]
CMD ["-XX:+UnlockExperimentalVMOptions","-Djava.net.preferIPv4Stack=true","-XX:+UseCGroupMemoryLimitForHeap","-XshowSettings:vm","-Djava.security.egd=file:/dev/./urandom","-jar","/beaconctl.jar"]
COPY beacon-beaconctl-*-all.jar /beaconctl.jar
